<?php 

    $action = $this->getAction();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo (isset($this->page_title) ? $this->page_title : 'Welcome to my site'); ?></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <link rel="stylesheet" href="/style.css">
</head>
<body>
    <nav>
        <ul>
            <li>THE DEVELOPER ASSIGNMENT</li>
        </ul>
    </nav>

    <div class="container d-flex flex-wrap justify-content-around align-items-center" style="height: 80vh">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">View Employee List</h5>
                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima reprehenderit quo necessitatibus voluptatem.</p>
                <a href="/employees" class="btn btn-primary">Employees</a>
            </div>
        </div>

        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">View Jobs Available</h5>
                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima reprehenderit quo necessitatibus voluptatem.</p>
                <a href="/jobs" class="btn btn-primary">Jobs</a>
            </div>
        </div>

        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">View Departments</h5>
                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima reprehenderit quo necessitatibus voluptatem.</p>
                <a href="/departments" class="btn btn-primary">Departments</a>
            </div>
        </div>
    </div>

<?php include VIEW . 'footer.phtml'; ?>