<?php include VIEW . 'header.phtml'; ?>
<div class="container">

    <div class="page-header">
        <h1>
            Employees 
        </h1>
    </div>

    <?php 

        if(array_key_exists('employees', $this->view_data)) {
            
            $table = "<table class='table table-striped'>";
            $table .= '<thead>
                            <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Job</th>
                            <th scope="col">Email</th>
                            </tr>
                        </thead>';
            foreach($this->view_data['employees'] as $employee) {
                $table .= "<tr class='clickable-row' data-href='employees/index/". $employee['employee_id'] ."'>";
                $table .= '<td>' . $employee['last_name'] . ', ' . $employee['first_name'] . '</td>';
                $table .= '<td>' . $employee['job_title'] . '</td>';
                $table .= '<td>' . $employee['email'] . '</td>';
                $table .= '</tr>';
            }

            $table .= '</table>';

            echo $table;

        }

    ?>
</div>
<?php include VIEW . 'footer.phtml'; ?>