<?php include VIEW . 'header.phtml'; ?>
<div class="container">

    <div class="page-header">
        <h1>
            Jobs 
        </h1>
    </div>

    <?php 

        if(array_key_exists('jobs', $this->view_data)) {
            
            $table = "<table class='table table-striped'>";
            $table .= '<thead>
                            <tr>
                            <th scope="col">Title</th>
                            <th scope="col">Min Salary</th>
                            <th scope="col">Max Salary</th>
                            </tr>
                        </thead>';
            foreach($this->view_data['jobs'] as $job) {
                $table .= "<tr>";
                $table .= '<td>' . $job['job_title'] . '</td>';
                $table .= '<td>' . $job['min_salary'] . '</td>';
                $table .= '<td>' . $job['max_salary'] . '</td>';
                $table .= '</tr>';
            }

            $table .= '</table>';

            echo $table;

        }

    ?>
</div>
<?php include VIEW . 'footer.phtml'; ?>