<?php include VIEW . 'header.phtml'; ?>
<div class="container">

    <div class="page-header d-flex align-items-center justify-content-between">
        <h1>
            Department Info 
        </h1>
        <a href="/employees" style="align: right">< Back to Employees</a>
    </div>

    <?php 

        if(array_key_exists('departments', $this->view_data)) {
            
            $table = "<table class='table table-striped'>";
            $table .= '<thead>
                            <tr>
                            <th scope="col">Department Name</th>
                            <th scope="col">Address</th>
                            </tr>
                        </thead>';
            foreach($this->view_data['departments'] as $department) {
                $table .= "<tr>";
                $table .= '<td>' . $department['department_name'] . '</td>';
                $table .= '<td>' . $department['street_address'] . ' ' . $department['city'] . ', ' . $department['state_province'] . ' ' . $department['postal_code'] . ' ' . $department['country_id'] . ' ' . '</td>';
                $table .= '</tr>';
            }

            $table .= '</table>';

            echo $table;

        }

    ?>
</div>
<?php include VIEW . 'footer.phtml'; ?>